---
- name: Install packages
  apt: name={{item}} state=present update-cache=yes cache_valid_time=864000
  become: true
  with_items:
    - htop
    - iotop
    - strace
    - sysstat
    - dstat
    - lsof
    - iputils-ping
    - telnet
    - dnsutils
    - tcpdump
    - iptraf
